module.exports = {
  rules: {
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'type-enum': [
      2,
      'always',
      [
        ':house: (build)',
        ':wrench:chore',
        ':construction_worker: (ci)',
        ':memo: (docs)',
        ':sparkles: (feat)',
        ':bug: (fix)',
        ':zap: (perf)',
        ':recycle: (refactor)',
        ':rewind: (revert)',
        ':art: (style)',
        ':white_check_mark: (test)',
      ],
    ],
    'scope-empty': [2, 'always'],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-max-length': [2, 'always', 50],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'body-leading-blank': [2, 'always'],
    'body-max-line-length': [2, 'always', 72],
    'footer-leading-blank': [2, 'always'],
    'footer-max-line-length': [2, 'always', 72],
  },
};
